packages:
  - apps/*
  - packages/*
  - packages/features/*

allowBuilds:
  '@scarf/scarf': false
  esbuild: true
  msw: false
  simple-git-hooks: false

minimumReleaseAgeExclude:
  - react-dom@19.2.8
  - react@19.2.8
