import type { DeviceTaskAction } from '../domain/task-actions';

export interface F09WorkflowPresentation {
  title: string;
  subtitle: string;
  step: string;
  stepMeta: string;
  alertTitle: string;
  alertBody: string;
  primaryLabel: string;
  secondaryLabel: string;
}

export const F09_WORKFLOWS: Record<DeviceTaskAction, F09WorkflowPresentation> = {
  WAREHOUSE_RECEIVE: {
    title: '扫码收货',
    subtitle: '扫描运单与包裹条码，核对预报和实收数据',
    step: '步骤 1/11 · 收货扫描',
    stepMeta: '重复扫码命中同一业务意图，不重复生成收货记录',
    alertTitle: '等待扫描运单或包裹',
    alertBody: '扫码枪 Enter、设备广播、相机和手工输入共用同一校验链路。',
    primaryLabel: '确认收货',
    secondaryLabel: '登记异常',
  },
  REWEIGH: {
    title: '称重 / 量方',
    subtitle: '设备读数稳定后复核重量，不允许静默覆盖',
    step: '步骤 2/11 · 收货数据采集',
    stepMeta: '电子秤 SCALE-SZX-02 · 量方仪 DIM-SZX-01',
    alertTitle: '等待稳定重量',
    alertBody: '允许人工复核；每次修正都保留来源和审计。',
    primaryLabel: '确认重量',
    secondaryLabel: '重新采集',
  },
  MEASURE_DIMENSIONS: {
    title: '称重 / 量方',
    subtitle: '设备读数必须稳定后才能确认',
    step: '步骤 2/11 · 收货数据采集',
    stepMeta: '电子秤 SCALE-SZX-02 · 量方仪 DIM-SZX-01',
    alertTitle: '设备读数稳定',
    alertBody: '允许人工复核，不允许静默覆盖。',
    primaryLabel: '确认读数',
    secondaryLabel: '重新采集',
  },
  CAPTURE_RECEIPT_PHOTO: {
    title: '拍照与媒体预留',
    subtitle: '业务事件与证据在同一作用域中安全提交',
    step: '步骤 3/11 · 证据 3/6',
    stepMeta: '最多 6 张；压缩后保留内容哈希',
    alertTitle: '媒体 reservation 已接受',
    alertBody: 'UPLOADED 仅代表服务端预留，业务仍需 APPLIED / DUPLICATE 回执。',
    primaryLabel: '确认并上架',
    secondaryLabel: '删除重拍',
  },
  PUTAWAY: {
    title: '扫描上架',
    subtitle: '先扫货物，再扫目标库位',
    step: '步骤 4/11 · 待上架 6',
    stepMeta: '推荐库位 RCV-20260723-01',
    alertTitle: '货物已锁定',
    alertBody: '重量与媒体数据已就绪，等待目标库位。',
    primaryLabel: '确认上架',
    secondaryLabel: '异常登记',
  },
  INVENTORY_MOVE: {
    title: '移库作业',
    subtitle: '扫描原库位、货物与目标库位完成三方校验',
    step: '步骤 5/11 · 移库 1 件',
    stepMeta: '来源库位 INV-LOC-1842',
    alertTitle: '原库位校验通过',
    alertBody: '目标库位必须与当前仓库、货物策略和容量一致。',
    primaryLabel: '确认移库',
    secondaryLabel: '取消',
  },
  SORT: {
    title: '扫描分拣',
    subtitle: '按渠道、目的地和波次校验分拣口',
    step: '步骤 6/11 · 波次 WAVE-0723-08',
    stepMeta: '需处理 18/24 · 异常 1',
    alertTitle: '格口匹配',
    alertBody: '扫描出库渠道、空运线路与目标格口。',
    primaryLabel: '确认分拣',
    secondaryLabel: '登记错分',
  },
  PICK: {
    title: '波次拣货',
    subtitle: '按照波次顺序完成库位、货物与数量校验',
    step: '步骤 7/11 · 拣货 18/24',
    stepMeta: '路线 01-08 → 02-04 → C01-02',
    alertTitle: '当前库位 6-01-08',
    alertBody: '核对货物和数量后进入下一库位。',
    primaryLabel: '确认拣货',
    secondaryLabel: '缺货异常',
  },
  BAG: {
    title: '装袋 / 托盘 / 容器',
    subtitle: '扫描容器与货物，完成装载归属校验',
    step: '步骤 8/11 · 装载单元',
    stepMeta: 'BAG-008 · 计划 6 件',
    alertTitle: '层级校验通过',
    alertBody: '袋、托、柜、容器均保留货物层级与审计。',
    primaryLabel: '确认装袋',
    secondaryLabel: '解绑修正',
  },
  PALLETIZE: {
    title: '装袋 / 托盘 / 容器',
    subtitle: '扫描托盘与货物，完成装载归属校验',
    step: '步骤 8/11 · 装载单元',
    stepMeta: 'PLT-018 · 计划 18 件',
    alertTitle: '层级校验通过',
    alertBody: '确认后货物进入托盘层级，保留完整装载审计。',
    primaryLabel: '确认装托',
    secondaryLabel: '解绑修正',
  },
  CONTAINERIZE: {
    title: '装袋 / 托盘 / 容器',
    subtitle: '扫描柜号与装载单元，完成容量和归属校验',
    step: '步骤 8/11 · 装柜 18/20',
    stepMeta: 'CNT-SEGU1842 · 计划 20 件',
    alertTitle: '层级校验通过',
    alertBody: '确认后装载单元进入柜级，不在客户端推导版本。',
    primaryLabel: '确认装柜',
    secondaryLabel: '解绑修正',
  },
  DISPATCH: {
    title: '出库确认',
    subtitle: '完成作业码、装载单元与出库状态校验',
    step: '步骤 8.5/11 · 出库预检',
    stepMeta: '所有装载关系已核对',
    alertTitle: '出库预检通过',
    alertBody: '等待服务端权威回执后才更新业务状态。',
    primaryLabel: '确认出库',
    secondaryLabel: '查看差异',
  },
  STOCKTAKE: {
    title: '盘点作业',
    subtitle: '扫描库位与货物，记录实盘数量',
    step: '步骤 5.5/11 · 库位盘点',
    stepMeta: '差异必须提交原因并进入审计',
    alertTitle: '等待实盘数量',
    alertBody: '盘点结果不直接覆盖库存，交由服务端命令确认。',
    primaryLabel: '确认盘点',
    secondaryLabel: '登记差异',
  },
  LAST_MILE_INTAKE: {
    title: '尾程接货',
    subtitle: '核对站点、批次与接货清单',
    step: '步骤 9/11 · 尾程接货',
    stepMeta: '任务 LM-1842 · 状态 PLANNED',
    alertTitle: '尾程任务已锁定',
    alertBody: '服务端确认接货后才进入可打托状态。',
    primaryLabel: '确认接货',
    secondaryLabel: '报告异常',
  },
  LAST_MILE_PALLETIZE: {
    title: '尾程打托',
    subtitle: 'PLANNED → PALLETIZED · 只采用服务端权威回执',
    step: '步骤 9/11 · 配送任务 LM-1842',
    stepMeta: '路线 12 · 站点 NorthLine',
    alertTitle: '配送任务已接收',
    alertBody: '扫描托盘和任务，服务端校验 canonical 状态。',
    primaryLabel: '确认打托',
    secondaryLabel: '配送异常',
  },
  LAST_MILE_LOAD: {
    title: '尾程装车',
    subtitle: 'PALLETIZED → LOADED · 扫车码、托盘与封签',
    step: '步骤 9.2/11 · 装车 3/4 托',
    stepMeta: '任务 LM-1842 · 车辆粤 B·1842',
    alertTitle: '托盘与车辆匹配',
    alertBody: '装车后采用响应中的 LOADED / version。',
    primaryLabel: '确认装车',
    secondaryLabel: '卸下托盘',
  },
  LAST_MILE_DELIVER: {
    title: '派送执行',
    subtitle: 'LOADED → OUT_FOR_DELIVERY · 地址与收件人复核',
    step: '步骤 10/11 · 第 6/18 站',
    stepMeta: '预计抵达 10:35 · 距离 3.2 km',
    alertTitle: '已到达服务范围',
    alertBody: 'GPS 仅作现场辅助证据，不在客户端推导状态。',
    primaryLabel: '到达并交付',
    secondaryLabel: '无法交付',
  },
  LAST_MILE_EXCEPTION: {
    title: '派送异常',
    subtitle: '异常证据与业务事件同一作用域保留',
    step: '步骤 10/11 · 异常登记',
    stepMeta: '主链状态保持服务端权威',
    alertTitle: '需要异常证据',
    alertBody: '异常类型、说明和媒体缺一不可。',
    primaryLabel: '提交异常',
    secondaryLabel: '返回派送',
  },
  CAPTURE_POD: {
    title: '签收与 POD',
    subtitle: '创建不可变 POD 版本，修正使用 amended 追加',
    step: '步骤 11/11 · 证据 2/2',
    stepMeta: '签名、照片与 GPS 已采集',
    alertTitle: '签收信息完整',
    alertBody: '媒体必须取得 reservation 后才能提交业务命令。',
    primaryLabel: '确认签收',
    secondaryLabel: '补充证据',
  },
};

export function f09Workflow(action: DeviceTaskAction) {
  return F09_WORKFLOWS[action];
}
