export type OpsFlowId = 'F02' | 'F03' | 'F04' | 'F05' | 'F06' | 'F07' | 'F10';

export interface OpsFlowStateDefinition {
  id: string;
  label: string;
  title: string;
  description: string;
  evidence: string[];
  tone: 'info' | 'warning' | 'danger';
  role: 'alert' | 'status';
  primaryAction?: string;
  actionFeedback?: string;
  recoverOnPrimary?: boolean;
}

export interface OpsFlowDefinition {
  id: OpsFlowId;
  label: string;
  states: OpsFlowStateDefinition[];
}

const normal = (label: string): OpsFlowStateDefinition => ({
  id: 'normal',
  label: '正常',
  title: `${label}正常`,
  description: '当前业务数据、权限和版本均可继续处理。',
  evidence: [],
  tone: 'info',
  role: 'status',
});

export const opsFlowCatalog: Record<OpsFlowId, OpsFlowDefinition> = {
  F02: {
    id: 'F02',
    label: 'F02 · 多渠道报价',
    states: [
      normal('报价'),
      {
        id: 'failed-no-rate',
        label: '无适用报价',
        title: '暂无适用报价',
        description: '输入内容已保留；被排除规则和可修复字段可逐项查看。',
        evidence: ['缺失目的地邮编末段', '单件重量超过空运限制', '可切换洛杉矶替代仓'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '定位缺失字段',
        actionFeedback: '已定位 3 个可修复字段',
      },
      {
        id: 'stale-rate',
        label: '价卡更新',
        title: '报价规则已发布新版本',
        description: '旧结果保持可追溯，明确接受后才按 v19 生成新报价。',
        evidence: ['当前快照 v18', '服务器价卡 v19', '预计销售价变化 +2.4%'],
        tone: 'warning',
        role: 'alert',
        primaryAction: '比较规则 diff',
        actionFeedback: '规则差异已展开',
      },
      {
        id: 'masked-cost',
        label: '成本脱敏',
        title: '成本与利润字段已脱敏',
        description: '当前角色仍可比较销售价、时效和限制；复制与导出使用同一字段策略。',
        evidence: ['成本 ••••••', '毛利 •••••• / •••', '策略 quote.cost.read = DENY'],
        tone: 'warning',
        role: 'status',
      },
      {
        id: 'expired',
        label: '报价过期',
        title: '报价已过有效期',
        description: '过期快照禁止接受；按当前规则重算后会生成新的不可变版本。',
        evidence: ['原报价快照 QV-20260723-18', '原金额 CNY 5,320.00', '17:30 已过期'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '按当前规则重算',
        actionFeedback: '已按当前规则生成新报价',
        recoverOnPrimary: true,
      },
    ],
  },
  F03: {
    id: 'F03',
    label: 'F03 · 收货差异',
    states: [
      normal('收货差异'),
      {
        id: 'failed-missing-evidence',
        label: '证据缺失',
        title: '问题件无法关闭',
        description: '关闭命令未提交，运单测量和补资料能力保持可用。',
        evidence: ['缺少整箱正面照片', '缺少重量读数照片', '规则 EVIDENCE-06'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '补拍并重试',
        actionFeedback: '补拍任务已创建',
      },
      {
        id: 'stale',
        label: '解决并发',
        title: '问题件版本已变化',
        description: '客户补资料与操作员关闭同时发生，旧结论不会覆盖新证据。',
        evidence: ['本地版本 v7', '服务器版本 v8', '客户新增 2 张照片'],
        tone: 'warning',
        role: 'alert',
      },
      {
        id: 'forbidden',
        label: '客户权限',
        title: '内部处理字段不可修改',
        description: '客户只可补资料和评论，不能修改责任、结论与内部备注。',
        evidence: ['issue.manage = DENY', '公开评论 = ALLOW'],
        tone: 'warning',
        role: 'alert',
      },
      {
        id: 'partial-notify',
        label: '通知部分失败',
        title: '问题件已创建，通知失败',
        description: '业务提交成功且不回滚；失败通知 Job 可独立重试。',
        evidence: ['ISS-260723-019 = OPEN', 'Job NTF-260723-92 = FAILED'],
        tone: 'warning',
        role: 'status',
        primaryAction: '重试通知',
        actionFeedback: '通知 Job 已重新排队',
      },
    ],
  },
  F04: {
    id: 'F04',
    label: 'F04 · 订舱装载',
    states: [
      normal('订舱装载'),
      {
        id: 'failed-incompatible',
        label: '兼容失败',
        title: '装载兼容性失败',
        description: '3 票运单不符合当前订舱、目的地或危险品约束。',
        evidence: ['S2505120031：目的地不符', 'S2505120042：危险品标签缺失', '原装载单未改变'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '下载失败报告',
        actionFeedback: '失败报告已生成',
      },
      {
        id: 'stale-load',
        label: '装载并发',
        title: '装载任务已被他人更新',
        description: '当前命令未覆盖服务器版本，封装后禁止静默增删。',
        evidence: ['本地版本 7', '服务器版本 8', '陈敏已移除 1 票运单'],
        tone: 'warning',
        role: 'alert',
      },
      {
        id: 'forbidden-release',
        label: '放货权限',
        title: '信用扣货：缺少放货权限',
        description: '普通出仓权限不能解除信用扣货，页面不提供确认放货动作。',
        evidence: ['缺失动作 hold.release', '欠款 CNY 86,420', '需要财务复核'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '发起放货审批',
        actionFeedback: '放货审批已创建',
      },
      {
        id: 'danger-dispatch',
        label: '出仓确认',
        title: '出仓危险确认',
        description: '确认后装载单封装并出仓，下游通知和审计立即生效。',
        evidence: ['42 票 / 5,187.20 kg', '未关闭问题 2 项', '打印完成 40 / 42'],
        tone: 'warning',
        role: 'alert',
        primaryAction: '进入二次确认',
        actionFeedback: '二次确认已打开',
      },
    ],
  },
  F05: {
    id: 'F05',
    label: 'F05 · 轨迹问题件',
    states: [
      normal('轨迹'),
      {
        id: 'failed-carrier',
        label: '承运商失败',
        title: '承运商轨迹同步失败',
        description: '最后成功轨迹保持不变，系统按退避计划重试。',
        evidence: ['GATEWAY_TIMEOUT', '最后同步 14:28', '下次重试 15:05'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '立即重试',
        actionFeedback: '同步任务已重新排队',
      },
      {
        id: 'out-of-order',
        label: '乱序去重',
        title: '轨迹乱序与重复已处理',
        description: '迟到事件已插入正确时间点，重复事件命中幂等结果。',
        evidence: ['回插 2 条', '去重 4 条', '业务状态未倒退'],
        tone: 'info',
        role: 'status',
      },
      {
        id: 'forbidden-internal',
        label: '客户脱敏',
        title: '内部轨迹详情不可见',
        description: '责任、成本和私密备注不会返回客户视图。',
        evidence: ['issue.internal.read = DENY', 'finance.cost.read = DENY'],
        tone: 'warning',
        role: 'alert',
      },
      {
        id: 'partial-notify',
        label: '通知部分失败',
        title: '工单已关闭，客户通知失败',
        description: '关闭结果不回滚，只重试通知 Job。',
        evidence: ['工单 CLOSED', 'SLA 已停止', '通知 NTF-260723-91 失败'],
        tone: 'warning',
        role: 'status',
        primaryAction: '重试通知',
        actionFeedback: '客户通知已重新排队',
      },
    ],
  },
  F06: {
    id: 'F06',
    label: 'F06 · 应收核销',
    states: [
      normal('应收核销'),
      {
        id: 'failed-payment',
        label: '支付失败',
        title: '支付失败，账单未改变',
        description: '可创建新支付订单，旧支付记录仍可追溯。',
        evidence: ['BANK_DECLINED', '账单余额 CNY 2,320.00'],
        tone: 'danger',
        role: 'alert',
      },
      {
        id: 'idempotent',
        label: '回调幂等',
        title: '支付回调已幂等处理',
        description: '同一微信交易只入账一次，重复与乱序回调返回原结果。',
        evidence: ['WX202607230018', '重复回调 3 次', '新增入账 0.00'],
        tone: 'info',
        role: 'status',
      },
      {
        id: 'stale-allocate',
        label: '核销并发',
        title: '可分配余额已被他人更新',
        description: '后提交者按版本被拒绝，刷新后显示当前可分配金额。',
        evidence: ['本地 v11', '服务器 v12', '当前可分配 CNY 680.00'],
        tone: 'warning',
        role: 'alert',
      },
      {
        id: 'danger-unreview',
        label: '反审核确认',
        title: '撤销核销与反审核确认',
        description: '操作影响账单、支付分配与会计期间，必须填写原因并二次确认。',
        evidence: ['解除分配 CNY 2,320.00', '期间 2026-07 需要重算'],
        tone: 'warning',
        role: 'alert',
        primaryAction: '查看影响范围',
        actionFeedback: '已展开账单与期间影响',
      },
    ],
  },
  F07: {
    id: 'F07',
    label: 'F07 · 应付导入',
    states: [
      normal('应付导入'),
      {
        id: 'failed-import',
        label: '导入失败',
        title: '应付导入预校验失败',
        description: '错误定位到工作表、行和列；批次未写入费用。',
        evidence: ['Sheet 应付明细', 'Row 183 / Column F', '费用编码缺失'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '下载错误报告',
        actionFeedback: '错误报告已生成',
      },
      {
        id: 'partial',
        label: '部分提交',
        title: '部分提交边界已确认',
        description: '成功 98 条，失败 2 条；失败项保持待修复，不重复成功写入。',
        evidence: ['成功清单 98 条', '失败清单 2 条', '回滚边界 BATCH-20260723-20'],
        tone: 'warning',
        role: 'status',
        primaryAction: '只重试失败项',
        actionFeedback: '失败清单已保留，等待重新校验',
      },
      {
        id: 'stale-cost',
        label: '成本并发',
        title: '已审核成本发生并发变化',
        description: '已审核成本不会被导入覆盖，差异转为调整建议。',
        evidence: ['本地版本 30', '服务器版本 31', '已保护 8 条'],
        tone: 'warning',
        role: 'alert',
      },
      {
        id: 'forbidden-pay',
        label: '付款分权',
        title: '付款操作需要独立审批',
        description: '制单权限不能付款，最终动作要求审批和再认证。',
        evidence: ['finance.pay.execute = DENY', '审批节点 2 / 3'],
        tone: 'danger',
        role: 'alert',
      },
    ],
  },
  F10: {
    id: 'F10',
    label: 'F10 · AI 智能导入',
    states: [
      normal('AI 导入'),
      {
        id: 'low-confidence',
        label: '低置信度',
        title: '4 个字段置信度不足',
        description: 'AI 建议未自动应用，请对照来源列选择候选字段。',
        evidence: ['模型 Zhili-Map 2.1', '提示版本 prompt-17', '最低置信度：收件州 42%'],
        tone: 'warning',
        role: 'alert',
        primaryAction: '进入人工映射',
        actionFeedback: '手工映射模式已开启',
      },
      {
        id: 'failed-model',
        label: '模型失败',
        title: 'AI 映射模型暂时不可用',
        description: '文件和手工映射能力已保留，重试沿用原 importJobId。',
        evidence: ['MODEL_TIMEOUT', '原始文件已保留'],
        tone: 'danger',
        role: 'alert',
        primaryAction: '进入手工映射',
        actionFeedback: '手工映射模式已开启',
      },
      {
        id: 'forbidden',
        label: '权限拦截',
        title: '权限策略阻止 AI 写入',
        description: 'AI 不越过调用者字段权限，金额和状态进入审批。',
        evidence: ['order.import.approve = DENY', '受限字段 8 项'],
        tone: 'danger',
        role: 'alert',
      },
      {
        id: 'rollback',
        label: '批次回滚',
        title: '回滚 AI 导入批次',
        description: '撤销可逆写入，保留模型输出、人工修改和最终 diff。',
        evidence: ['可逆写入 1,238 条', '外部副作用 2 项', '审计永久保留'],
        tone: 'warning',
        role: 'alert',
        primaryAction: '查看回滚边界',
        actionFeedback: '已展开外部副作用与回滚清单',
      },
    ],
  },
};
